### ISSUE TITLE
error: agent head missing

### ISSUE THREAD

**Issue by LZinsmeister** [samtecspg/articulate#348]
### Issues
I have started Articulate with the BotSharp platform through a docker-compose command: docker-compose -f dockerfiles/docker-compose-articulateui.yml up

On my localhost port 3000 the Articulate UI is shown, but nothing is working since I get the following error: 

"We couldn't connect to the API. This could be because the API ports aren't configured properly in your environment. For configuration instruction go to here:"

and the following link https://samtecspg.github.io/articulate/.
However in the documentation I cannot find how to fix this issue. Can you help me?

- I downloaded the Articulate release from https://github.com/Oceania2018/BotSharp
- I am running on windows
- I am running locally (on localhost:3000)
- I am using Mozilla Firefox and have tried on Chrome as well

----

**Comment by wrathagom** [comment]
Which version of windows and Docker?

**Comment by LZinsmeister** [comment]
Windows 10 and Docker Version 18.06.1-ce-win73 (19507)

**Comment by wrathagom** [comment]
Ah, I see the problem. It looks like Oceania isn't including the API in his compose fil. Can you try adding this service to your docker-compose.yml and seeing if that fixes your problem:

```
  api:
    image: samtecspg/articulate-api:0.12.1
    ports: ['0.0.0.0:7500:7500']
    networks: ['botsharp-network']
    entrypoint: ['node', 'start.js']
    environment:
     - SWAGGER_BASE_PATH
```

**Comment by LZinsmeister** [comment]
I added your code into docker-compose-articulateui.yml like so:

```
version: '3.0'

services:
  ui:
    image: samtecspg/articulate-ui:0.12.1
    ports: ['0.0.0.0:3000:3000']
    networks: ['botsharp-network']
    environment:
     - API_URL

  botsharp:
    image: botsharpdocker/botsharp-rasa:latest
    ports: ['0.0.0.0:5000:5000']
    networks: ['botsharp-network']

  api:
    image: samtecspg/articulate-api:0.12.1
    ports: ['0.0.0.0:7500:7500']
    networks: ['botsharp-network']
    entrypoint: ['node', 'start.js']
    environment:
     - SWAGGER_BASE_PATH

networks: {botsharp-network: {}}
```
However, when i run `docker-compose -f dockerfiles/docker-compose-articulateui.yml up` I get an error, namely "NotSpecified: (Pulling api (sa...-api:012.1)...:String) []. RemoteException". (I am using WindowsPowerShell ISE by the way).

**Comment by wrathagom** [comment]
yeah I don't think that is an Articulate error.

Here's a few threads:
 - https://github.com/docker/compose/issues/5222
 - https://stackoverflow.com/questions/2095088/error-when-calling-3rd-party-executable-from-powershell-when-using-an-ide

One of the suggested workarounds is to re-direct error output, not certain if that will work for you or not.

```
docker-compose -f dockerfiles/docker-compose-articulateui.yml up 2> $null
```

**Comment by LZinsmeister** [comment]
Hi Caleb, I was a bit too quick with my last post. The docker compose works, but I still get the same error as before:

"We couldn't connect to the API. This could be because the API ports aren't configured properly in your environment. For configuration instruction go to here:"

Any more suggestions?

**Comment by wrathagom** [comment]
what is the output of `docker-compose ps`? and you did say your running Docker for Windows not Docker Toolbox right?

**Comment by LZinsmeister** [comment]
Below the output op docker-compose ps

```
         Name                      Command             State            Ports         
--------------------------------------------------------------------------------------
dockerfiles_api_1        node start.js                 Exit 1                         
dockerfiles_botsharp_1   dotnet BotSharp.WebHost.dll   Up       0.0.0.0:5000->5000/tcp
dockerfiles_ui_1         yarn start                    Up       0.0.0.0:3000->3000/tcp
```

**Comment by wrathagom** [comment]
hmm so the api failed to start/didn't stay running any logs? `docker-compose logs api`

**Comment by LZinsmeister** [comment]
Below the output of `docker-compose logs api`
```
Attaching to dockerfiles_api_1
[36mapi_1       |[0m Failed during initialization
[36mapi_1       |[0m { Error: Redis connection in broken state: connection timeout exceeded.
[36mapi_1       |[0m     at RedisClient.connection_gone (/usr/src/app/node_modules/redis/index.js:649:19)
[36mapi_1       |[0m     at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:410:10)
[36mapi_1       |[0m     at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:279:14)
[36mapi_1       |[0m     at emitOne (events.js:96:13)
[36mapi_1       |[0m     at Socket.emit (events.js:189:7)
[36mapi_1       |[0m     at connectErrorNT (net.js:1025:8)
[36mapi_1       |[0m     at _combinedTickCallback (internal/process/next_tick.js:74:11)
[36mapi_1       |[0m     at process._tickCallback (internal/process/next_tick.js:98:9)
[36mapi_1       |[0m   code: 'CONNECTION_BROKEN',
[36mapi_1       |[0m   origin: 
[36mapi_1       |[0m    { Error: Redis connection to redis:6379 failed - getaddrinfo ENOTFOUND redis redis:6379
[36mapi_1       |[0m        at errnoException (dns.js:28:10)
[36mapi_1       |[0m        at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
[36mapi_1       |[0m      code: 'ENOTFOUND',
[36mapi_1       |[0m      errno: 'ENOTFOUND',
[36mapi_1       |[0m      syscall: 'getaddrinfo',
[36mapi_1       |[0m      hostname: 'redis',
[36mapi_1       |[0m      host: 'redis',
[36mapi_1       |[0m      port: 6379 } }
[36mapi_1       |[0m process.exit(1)
```

**Comment by wrathagom** [comment]
duh, okay so long story short the Botsharp docker compose file was missing a lot of elements. It needs the API, Duckling, and Redis. Because BotSharp only replaces rasa.

```
version: '3.0'

services:
  ui:
    image: samtecspg/articulate-ui:0.12.1
    ports: ['0.0.0.0:3000:3000']
    networks: ['botsharp-network']
    environment:
     - API_URL

  botsharp:
    image: botsharpdocker/botsharp-rasa:latest
    ports: ['0.0.0.0:5000:5000']
    networks: ['botsharp-network']

  api:
    image: samtecspg/articulate-api:0.12.1
    ports: ['0.0.0.0:7500:7500']
    networks: ['botsharp-network']
    entrypoint: ['node', 'start.js']
    environment:
     - SWAGGER_BASE_PATH

  duckling:
    image: samtecspg/duckling:0.1.6.0
    ports: ['0.0.0.0:8000:8000']
    networks: ['botsharp-network']

  redis:
    image: redis:4.0.6-alpine
    ports: ['0.0.0.0:6379:6379']
    networks: ['botsharp-network']
    command: redis-server --appendonly yes

networks: {botsharp-network: {}}
```
