### ISSUE TITLE
Docker not connecting to Articulate and api problem

### ISSUE THREAD

**Issue by RussellSPG** [samtecspg/articulate#571]
Since getting setup with docker, I was able to install the containers and get the services running from Articulate. However, when I tried localhost:3000 it would bring me to the Arty page, but no functionality. Cory and I were trying to get it working by reinstalling it, trying different versions (I used master, plus the one on releases page, and each version would get me the same result.
Connecting to localhost 7500 would give a 404 error.

Cory tried using his windows 10 on gitbash(I tried as well) and we got:
```
coryh@NA-CORYH MINGW64 ~/Documents/GitSome/articulate (master)
$ docker-compose up
Pulling ui (samtecspg/articulate-ui:repo-head)...
repo-head: Pulling from samtecspg/articulate-ui
Pulling rasa (samtecspg/articulate-rasa:repo-head)...
repo-head: Pulling from samtecspg/articulate-rasa
Pulling duckling (samtecspg/duckling:0.1.6.0)...
0.1.6.0: Pulling from samtecspg/duckling
Pulling redis (redis:4.0.6-alpine)...
4.0.6-alpine: Pulling from library/redis
Pulling elasticsearch (docker.elastic.co/elasticsearch/elasticsearch:6.5.1)...
6.5.1: Pulling from elasticsearch/elasticsearch
Pulling api (samtecspg/articulate-api:repo-head)...
repo-head: Pulling from samtecspg/articulate-api
Creating articulate_elasticsearch_1 ... done
Creating articulate_ui_1            ... done
Creating articulate_redis_1         ... done
Creating articulate_duckling_1      ... done
Creating articulate_rasa_1          ... done

ERROR: for api  Container "cb83496d7ebe" is unhealthy.
Encountered errors while bringing up the project.
```
Seems theres a problem with the API

Will explore more troubleshooting for windows 10

**Comment by wrathagom** [comment]
Where is a copy of the 404 error? A screenshot of the arty page? Was the loading spinner showing or the buttons?

Did you try the command I told you to run earlier with env variables?

**Comment by RussellSPG** [comment]
On Master.. Localhost:3000

![image](https://user-images.githubusercontent.com/42249324/52597397-d6dab780-2e20-11e9-96d9-4c2f4e16f6df.png)

for 7500

![image](https://user-images.githubusercontent.com/42249324/52597430-eeb23b80-2e20-11e9-9cb0-7cad1648ea95.png)

**Comment by RussellSPG** [comment]
Entered in the ENV variables for the YML file on Master:
```
version: '2.2'

services:
  api:
    image: samtecspg/articulate-api:repo-head
    ports: ['0.0.0.0:7500:7500']
    networks: ['alpha-nlu-network']
    entrypoint: ['yarn', 'start']
    environment:
      - SWAGGER_HOST=localhost:7500
      - SWAGGER_BASE_PATH
      - SWAGGER_SCHEMES
    depends_on:
      elasticsearch:
        condition: service_healthy
  ui:
    image: samtecspg/articulate-ui:repo-head
    ports: ['0.0.0.0:3000:3000']
    networks: ['alpha-nlu-network']
    environment:
     - API_URL=http://localhost:7500
     - WS_URL=http://localhost:7500
```
This time on localhost:3000 I got completely blank page:
![image](https://user-images.githubusercontent.com/42249324/52598050-b875bb80-2e22-11e9-826c-6df3fb13af30.png)
Same result as the 7500 without the ENV variables in
