### ISSUE TITLE
Can't run UI instance remotely

### ISSUE THREAD

**Issue by devotionsolutions** [samtecspg/articulate#658]
Hello, I'm running articulate on Windows Docker. Everything is fine running on localhost, but I'm having some difficulties trying to run UI remotely

This is my docker-compose so far:

`version: '3.0'

services:
  api:
    image: samtecspg/articulate-api:0.21.2
    ports: ['7500:7500']
  ui:
    image: samtecspg/articulate-ui:0.21.2
    ports: ['3000:3000'] 
  rasa:
    image: samtecspg/articulate-rasa:0.21.2
    ports: ['5000:5000']
    volumes: ["${MODEL_DIR:-./local-storage/rasa/nlu-model}:/app/projects", "${RASA_CONFIG:-./local-storage/rasa/rasa-config.yml}:/app/config.yml", "./local-storage/rasa/logs:/app/logs"]
  duckling:
    image: samtecspg/duckling:0.1.6.0
    ports: ['8000:8000']
  redis:
    image: redis:4.0.6-alpine
    ports: ['6379:6379']
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA:-./local-storage/redis-data}:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_TAG:-6.5.1}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ['9200:9200']
    volumes:
      - ${ES_CONFIG:-./local-storage/elasticsearch/config/elasticsearch.yml}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_DATA:-./local-storage/elasticsearch/data}:/usr/share/elasticsearch/data
      - ${ES_DATA:-./local-storage/elasticsearch/docker-healthcheck.sh}:/usr/share/docker-healthcheck.sh
`

I've tried to modify the ports (based on readme):
ports: ['0.0.0.0:3000:3000'] networks: ['alpha-nlu-network'] 

But I have an error when trying to run docker composer up.

ERROR: Service "ui" uses an undefined network "alpha-nlu-network"

Any idea?
Thanks in advance,

**Comment by dcalvom** [comment]
Hi @devotionsolutions, I see somehow you added `networks: ['alpha-nlu-network']` but I'm not sure where. Could you check that you don't have it in your compose.

**Comment by devotionsolutions** [comment]
Thanks @dcalvom 
This is my docker-compose after adding the networks. I'm assuming that I'm missing something

```
version: '3.0'

services:
  api:
    image: samtecspg/articulate-api:0.21.2
    ports: ['0.0.0.0:7500:7500']
  ui:
    image: samtecspg/articulate-ui:0.21.2
    ports: ['0.0.0.0:3000:3000'] 
    networks: ['alpha-nlu-network'] 
  rasa:
    image: samtecspg/articulate-rasa:0.21.2
    ports: ['5000:5000']
    volumes: ["${MODEL_DIR:-./local-storage/rasa/nlu-model}:/app/projects", "${RASA_CONFIG:-./local-storage/rasa/rasa-config.yml}:/app/config.yml", "./local-storage/rasa/logs:/app/logs"]
  duckling:
    image: samtecspg/duckling:0.1.6.0
    ports: ['8000:8000']
  redis:
    image: redis:4.0.6-alpine
    ports: ['6379:6379']
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA:-./local-storage/redis-data}:/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_TAG:-6.5.1}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports: ['9200:9200']
    volumes:
      - ${ES_CONFIG:-./local-storage/elasticsearch/config/elasticsearch.yml}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_DATA:-./local-storage/elasticsearch/data}:/usr/share/elasticsearch/data
      - ${ES_DATA:-./local-storage/elasticsearch/docker-healthcheck.sh}:/usr/share/docker-healthcheck.sh

```
