### ISSUE TITLE
Sign up error 500

### ISSUE THREAD

**Issue by mordebip** [samtecspg/articulate#811]
When trying to register via the /login interface, the registration goes fine, but it returns an error 500 on the line

`await request.cookieAuth.set({ id: user.id, name: user.name, email: user.email });` (cookieAuth is undefined)
in api/app/lib/routes/user/user.create.route.js

in order to get it working, i had to add  this
   

```
server.auth.strategy('session', 'cookie', {
        password: 'password-should-be-32-characters',
        cookie: 'sid-example',
        redirectTo: '/login',
        isSecure: false,
        validateFunc: async (request, session) => {

            const cached = await cache.get(session.sid);
            const out = {
                valid: !!cached
            };

            if (out.valid) {
                out.credentials = cached.account;
            }

            return out;
        }
    });

```

Just before 
`await server.start();`
on the file api/app/server/index.js

but i can't yet say if it is the right implementation

**Comment by wrathagom** [comment]
You're on master right?

**Comment by mordebip** [comment]
Yes on master
the solution might be applicable to the login issue too

**Comment by wrathagom** [comment]
can you tell me how you're running? Everything in Docker? which env variables do you have set? @malave wrote the auth pieces so he'll be best to evaluate, but I am trying to make sure he has everything he needs when he gets on.

**Comment by mordebip** [comment]
Yes i always build a docker image, then i externalise the ui and api folder for my tests

i can't get the ui to connect to the api when setting the auth env 

so i define my env as following

ENV in api

```
SESSION_SECRET = secret
AUTH_PASSWORD = totololo
AUTH_ENABLED = **false**
AUTH_FORCE_DEFAULT_USER = true
AUTH_USER = admin@admin.com
```

ENV in ui

`AUTH_ENABLED = **false**`

**Comment by wrathagom** [comment]
externalize?

how are you connecting to the UI, or what address are you using?

**Comment by mordebip** [comment]
I'm mapping api   /usr/src/app   and ui /reactapp ol a local folder, the rest is unchanged according to the docker compose file 

```
version: '3.0'

services:
  nginx:
    container_name: nginx
    image: nginx:1.15.10-alpine
    volumes:
      - ./local-storage/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./local-storage/nginx/nginx-http.conf:/etc/nginx/nginx.conf
    ports: ['${PORT:-18080}:80']
    command: [nginx-debug, '-g', 'daemon off;']
  api:
    container_name: api
    image: mordeb:api
    ports: ['${API_PORT:-7500}:7500']
    environment:
      - SESSION_SECRET=L}nrF{k/&MG3P:Bt*^:F6ycd}4<qAdS-n
      - AUTH_USER=admin@admin.com
      - AUTH_PASSWORD=totololo123
      - AUTH_ENABLED=false
  ui:
    container_name: ui
    image: mordeb:ui
    environment:
      - AUTH_ENABLED=false

  rasa:
    container_name: rasa
    image: mordeb:rasa
    volumes: ["${MODEL_DIR:-./local-storage/rasa/nlu-model}:/app/projects", "${RASA_CONFIG:-./local-storage/rasa/rasa-config.yml}:/app/config.yml", "./local-storage/rasa/logs:/app/logs"]
  duckling:
    container_name: duckling
    image: mordeb:duckling
  redis:
    container_name: redis
    image: redis:4.0.6-alpine
    command: redis-server --appendonly yes
    volumes:
      - ${REDIS_DATA:-./local-storage/redis-data}:/data
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_TAG:-6.5.1}
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${ES_CONFIG:-./local-storage/elasticsearch/config/elasticsearch.yml}:/usr/share/elasticsearch/config/elasticsearch.yml
      - ${ES_DATA:-./local-storage/elasticsearch/data}:/usr/share/elasticsearch/data
      - ${ES_DATA:-./local-storage/elasticsearch/docker-healthcheck.sh}:/usr/share/docker-healthcheck.sh

```

ps : i have to map them after the creation, or the folders will be empty

concerning the build, i have an an sh file

```
cd articulate

cd ui
docker build -t "mordeb:ui" .
cd ../api
docker build -t "mordeb:api" .
cd ../rasa
docker build -t "mordeb:rasa" .
cd ../duckling
docker build -t "mordeb:duckling" .
cd ..
chown -R 1000:1000 local-storage/elasticsearch
docker-compose down && docker-compose up -d

```
